spring:
   application:
     name: "gateway-service"
   config:
     import: configserver:http://localhost:8888
   cloud:    
    gateway:
     # default-filters: - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      discovery:
          locator:
              enabled: true
          lower-case-service-id: true
          enabled: true
      globalcors:
        #cors-configurations:
           # '/**':
               #  allowed-origins: "http://localhost:4200"
               # allowed-methods: "*"
              #   allowed-headers: "*"
               #  allow-credentials: true
       # add-to-simple-url-handler-mapping:
eureka:
    instance:
          preferIpAddress: true
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:4200"
        allow-credentials: true
        allowed-headers: *
        allowed-methods: *
        exposed-headers: {"Access-Control-Expose-Headers", "Access-Control-Allow-Origin, Access-Control-Allow-Credentials, Authorization"}

